version: "3.8"
services: 
  playwright-test:
    image: playwright-test-yx11
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run pageObjects-firefox
    volumes:
      - ./playwright-report/:/app/playwright-report
      - ./test-results/:/app/test-results